# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sateesh Kumar Peddoju  
email: <a href="mailto:sateesh@ieee.org">sateesh@ieee.org</a>
description: >- # this means to ignore newlines until "baseurl:"
  Sateesh Kumar Peddoju, IIT Roorkee, India.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  drpskfec

# Build settings
markdown: kramdown
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"

search: false

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

repository: drpskfec/drpskfec.github.io

defaults:
  # _posts
  - scope:
      path: ""
      type: home
    values:
      author_profile: true

author:
  name   : "Sateesh K Peddoju, Ph. D"
# avatar : "images/profile.jpg"
  avatar : "images/psk-passport-photo.png"
  bio    : "Senior Member ACM <br> Senior Member IEEE <br><br> Associate Professor <br> <a href=\"https://www.iitr.ac.in/departments/CSE/pages/index.html\">Dept. of CSE</a>, <a href=\"https://www.iitr.ac.in\">IIT Roorkee</a>"
        #uri    : "www.peddoju.com"
  location : "S-229, E&C Building, IIT Roorkee"
  linkedin: peddojusateesh
  facebook: peddojusateesh
  googlescholar: https://scholar.google.com/citations?hl=en&user=iMMhgycAAAAJ&view_op=list_works&sortby=pubdate
  phone: (+91) 1332-28-5647
  
  #dblp: http://dblp.uni-trier.de/pers/hd/p/Peddoju:Sateesh_Kumar onclick="window.open(&quot;http://dblp.uni-trier.de/pers/hd/p/Peddoju:Sateesh_K=&quot;); window.open(&quot;http://dblp2.uni-trier.de/pers/hd/k/Kumar:P=_Sateesh&quot;);"
  dblp: http://dblp.uni-trier.de/pers/hd/p/Peddoju:Sateesh_Kumar
  dblp1: http://dblp.uni-trier.de/pers/hd/p/Peddoju:Sateesh_K=
  dblp2: http://dblp2.uni-trier.de/pers/hd/k/Kumar:P=_Sateesh

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - google_scholar.rb
  - generate_pubs.rb
  - tex2html.rb
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

theme: jekyll-theme-minimal
minimal_mistakes_skin: "aqua" # "default", "air", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
